config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'landing_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create', as: :auth_callback
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:index, :show, :create, :destroy] do
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  resources :notifications,       only: [:index, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  has_many :notifications, dependent: :destroy
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :logged_in_user

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    @micropost.create_notification_comment(current_user, @comment.id)
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    render :index
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :micropost_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: [micropost, comment], url: micropost_comments_path(@micropost)) do |f| %>
      <%= f.text_area :content, class: "input-mysize" %>
      <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
    <% end %>
  </div>
</div>

app/views/comments/_index.html.erb
<% provide(:title, "Comment") %>

<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <p><%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %></p>
    <p>コメント：<%= comment.content %></p>
    <% if comment.user == current_user %>
      <p><%= link_to 'コメントを削除する', micropost_comment_path(comment.micropost_id, comment.id), method: :delete, remote: true %></p>
    <% end %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.micropost.comments }) %>")
$("textarea").val('')